nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://127.0.0.1:3000']  # L'adresse de votre frontend React
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']  # Méthodes autorisées
        max_age: 3600
    paths:
        '^/api/': ~  # Appliquer CORS uniquement sur les routes API