controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
app_default:
  path: "/"
  controller: 'App\Controller\IndexController::index'

app_get_current_user:
  path: "/getCurrentUser"
  controller: 'App\Controller\IndexController::getCurrentUser'
  methods: GET

app_register_credentials:
  path: "/registerCredentials"
  controller: 'App\Controller\AuthController::registerCredentials'
  methods: POST

app_login_credentials:
  path: "/loginCredentials"
  controller: 'App\Controller\AuthController::loginCredentials'
  methods: POST

logout_route:
  path: /logout
  methods: GET

resultats:
  path: /resultat
  controller: 'App\Controller\IndexController::resultat'
  methods: GET

resultats_city:
  path: /resultat/{city}
  controller: 'App\Controller\IndexController::resultat'
  methods: GET

vols:
  path: /vols
  controller: 'App\Controller\IndexController::vols'
  methods: GET

hebergement:
  path: /hebergement
  controller: 'App\Controller\IndexController::hebergement'
  methods: GET