controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

app_default:
  path: "/"
  controller: 'App\Controller\IndexController::index'

add_user:
  path: "/add"
  controller: 'App\Controller\UserController::addUser'
  methods: POST

app_react:
  path: /{reactRouting}
  controller: App\Controller\IndexController::index
  requirements:
    # reactRouting: .*

api_users:
    path: /api/users
    controller: App\Controller\APIController::getUsers
    methods: [GET, POST]
