controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

app_default:
  path: "/"
  controller: 'App\Controller\IndexController::index'

app_profil:
  path: "/profil"
  controller: 'App\Controller\IndexController::profil'

app_insert_data:
  path: "/insert-user-data"
  controller: 'App\Controller\DataController::insertData'

api_user_list:
  path: "/userlist"
  controller: 'App\Controller\DataController::displayAllUsers'