controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
app_default:
  path: "/"
  controller: 'App\Controller\IndexController::index'

app_profil:
  path: "/profil"
  controller: 'App\Controller\IndexController::profil'

app_vols:
  path: "/vols/page"
  controller: 'App\Controller\IndexController::vols'

app_get_current_user:
  path: "/getCurrentUser"
  controller: 'App\Controller\IndexController::getCurrentUser'
  methods: GET

app_register_credentials:
  path: "/registerCredentials"
  controller: 'App\Controller\AuthController::registerCredentials'
  methods: POST

app_login_credentials:
  path: "/loginCredentials"
  controller: 'App\Controller\AuthController::loginCredentials'
  methods: POST

logout_route:
  path: /logout
  methods: GET

google_callback:
  path: /google/callback
  controller: App\Controller\GoogleController::callback

app_show_companies:
  path: /showCompanies
  controller: App\Controller\CompanyController::showCompanies
  methods: GET

app_add_company:
  path: /addCompany
  controller: App\Controller\CompanyController::addCompany
  methods: [POST, PUT]

app_delete_company:
  path: /deleteCompany
  controller: App\Controller\CompanyController::deleteCompany
  methods: [POST, DELETE]

app_show_disliked_hotels:
  path: /showDislikedHotels
  controller: App\Controller\HotelController::showDislikedHotels
  methods: GET

app_add_disliked_hotel:
  path: /addDislikedHotel
  controller: App\Controller\HotelController::addDislikedHotel
  methods: [POST, PUT]

app_delete_disliked_hotel:
  path: /deleteDislikedHotel
  controller: App\Controller\HotelController::deleteDislikedHotel
  methods: [POST, DELETE]

app_show_favoite_hotels:
  path: /showFavoriteHotels
  controller: App\Controller\HotelController::showFavoiteHotels
  methods: GET

app_add_favoite_hotel:
  path: /addFavoriteHotel
  controller: App\Controller\HotelController::addFavoiteHotel
  methods: [POST, PUT]

app_delete_favoite_hotel:
  path: /deleteFavoriteHotel
  controller: App\Controller\HotelController::deleteFavoiteHotel
  methods: [POST, DELETE]

app_show_destinations:
  path: /showDestinations
  controller: App\Controller\DestinationController::showDestinations
  methods: GET

app_add_destination:
  path: /addDestination
  controller: App\Controller\DestinationController::addDestination
  methods: [POST, PUT]

app_delete_destination:
  path: /deleteDestination
  controller: App\Controller\DestinationController::deleteDestination
  methods: [POST, DELETE]

app_modify_destination:
  path: /modifyDestination
  controller: App\Controller\DestinationController::modifyDestination
  methods: [POST, UPDATE]

app_show_travelers:
  path: /showTravelers
  controller: App\Controller\TravelerController::showTravelers
  methods: GET

app_add_traveler:
  path: /addTraveler
  controller: App\Controller\TravelerController::addTraveler
  methods: [POST, PUT]

app_delete_traveler:
  path: /deleteTraveler
  controller: App\Controller\TravelerController::deleteTraveler
  methods: [POST, DELETE]

app_modify_traveler:
  path: /modifyTraveler
  controller: App\Controller\TravelerController::modifyTraveler
  methods: [POST, UPDATE]

app_show_airports:
  path: /showAirports
  controller: App\Controller\AirportController::showAirports
  methods: GET

app_add_airport:
  path: /addAirport
  controller: App\Controller\AirportController::addAirport
  methods: [POST, PUT]

app_delete_airport:
  path: /deleteAirport
  controller: App\Controller\AirportController::deleteAirport
  methods: [POST, DELETE]

app_show_fidelity_programs:
  path: /showFidelityPrograms
  controller: App\Controller\FidelityProgramController::showFidelityPrograms
  methods: GET

app_add_fidelity_program:
  path: /addFidelityProgram
  controller: App\Controller\FidelityProgramController::addFidelityProgram
  methods: [POST, PUT]

app_delete_fidelity_program:
  path: /deleteFidelityProgram
  controller: App\Controller\FidelityProgramController::deleteFidelityProgram
  methods: [POST, DELETE]

app_modify_fidelity_program:
  path: /modifyFidelityProgram
  controller: App\Controller\FidelityProgramController::modifyFidelityProgram
  methods: [POST, UPDATE]

app_show_user_profile:
  path: /showUserProfile
  controller: App\Controller\UserProfileController::showUserProfile
  methods: GET

app_update_user_profile:
  path: /updateUserProfile
  controller: App\Controller\UserProfileController::updateUserProfile
  methods: [POST, UPDATE]
