# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  google_client_id: '%env(GOOGLE_OAUTH_ID)%'
  google_client_secret: '%env(GOOGLE_OAUTH_SECRET)%'
  google_redirect_uri: '%env(GOOGLE_REDIRECT_URI)%'
  auth0_domain: '%env(AUTH0_DOMAIN)%'
  auth0_client_id: '%env(AUTH0_CLIENT_ID)%'
  auth0_client_secret: '%env(AUTH0_CLIENT_SECRET)%'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # GoogleController et GoogleAuthentiator configuration
  App\Controller\GoogleController:
    arguments:
      $clientId: "%env(GOOGLE_OAUTH_ID)%"
      $clientSecret: "%env(GOOGLE_OAUTH_SECRET)%"
      $redirectUri: "%env(GOOGLE_REDIRECT_URI)%"
    tags: ["controller.service_arguments"]

  App\Security\GoogleAuthenticator:
    arguments:
      $clientId: '%env(GOOGLE_OAUTH_ID)%'
      $clientSecret: '%env(GOOGLE_OAUTH_SECRET)%'
      $redirectUri: '%env(GOOGLE_REDIRECT_URI)%'

  # UserRepository configuration
  App\Repository\UserRepository:
    autowire: true
    autoconfigure: true
